// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"agnos/backend/src/api"
	"agnos/backend/src/usecase/password"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeServer() (*gin.Engine, error) {
	usecase := password.NewPasswordUsecase()
	apiHandler := api.NewAPIHandler(usecase)
	engine := ProvideServer(apiHandler)
	return engine, nil
}

// wire.go:

func ProvideServer(
	apiHandler *api.APIHandler,
) *gin.Engine {
	r := gin.Default()
	r.POST("/api/strong_password_steps", apiHandler.StrongPasswordSteps)
	return r
}
